services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: readmission
      POSTGRES_PASSWORD: readmission
      POSTGRES_DB: readmission
    ports:
      - "5432:5432"
    volumes:
      - readmission_pg:/var/lib/postgresql/data

volumes:
  readmission_pg:
